---
- name: Ensure all installed packages are up-to-date using APT module.
  ansible.builtin.apt:
    name: '*'
    state: latest  # noqa package-latest
    update_cache: true
    only_upgrade: true

- name: Ensure packages not needed are removed.
  ansible.builtin.apt:
    autoremove: true

- name: Check if reboot is required.
  ansible.builtin.stat:
    path: "/var/run/reboot-required"
  register: reboot_reg
  changed_when: reboot_reg.stat.exists == true
  notify: Reboot server
